### ISSUE TITLE
Slab/stair placing is very outdated

### ISSUE THREAD

**Issue by Fixer-007** [tenplus1/stairs#3]
There were a lot of changes in slab/stair placement method, this mod still uses old method, which is not really that convenient and requires lots of screwdriving.

**Comment by tenplus1** [comment]
Yeah, I kept the placement of stairs very simple by using "on_place = rotate_node" on purpose, many different rotations can be achieved by placing on bottom/side/top or by holding sneak when placing so that screwdriver is hardly needed.
